<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bryce Kratzer</title>
    <style>
        body {
            background-color: #f1e8df; /* Set the background color here */
        }
    </style>
</head>
<body>
    <pre>
        name: Bryce Kratzer
        age: 20
    </pre>
</body>
</html>
