theme: jekyll-theme-minimal
title: Bryce's Github Page
description: Welcome to my github page! More of my advanced projects will be posted on my github account.
skills:
- java 
- C
- HTML
- CSS
- Python
